version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=technical_test
      - POSTGRES_USER=hinky_wan
      - POSTGRES_PASSWORD=20241026
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
